### ISSUE TITLE
Suggestion: Matching success

### ISSUE THREAD

**Issue by brendan-pike** [Marekkon5/discogstagger#8]
I note that very frequently I have albums that are matched but one of two tracks fail.  Is it using an acoustic id to match?  But what ever the reason I was thinking it would be ideal to make an educated guess of the track, ie. if you've just matched 9 tracks in the same directory to the same album its an extremely high likely hood that the unmatched track with the track number 09 is the track from the same album.  So if that album has a track 09 we haven't yet matched its almost certainly a match.  My suggestion would be to treat it as matched but with a warning.

Not sure if I explained that well, let me know if the idea is not clear.

**Comment by Marekkon5** [comment]
It is using track title and artist name to match the song. I understand your idea, but the tagger doesn't keep any context about the songs / previously matched songs + sometimes they are even randomly sorted, due to the way they're loaded. I also think that  it's unreliable, because not everyone tags on this folder structure & track number isn't always present. I might consider it in future, but not now.

**Comment by brendan-pike** [comment]
Now worries, cheers
